#!/usr/bin/env python

# Load the pylit module::

import pylit

# Configure default settings, e.g. ::

#defaults.code_block_marker = '.. code-block:: python'

# call the pylit.py text <--> code converter::

pylit.main()
